config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :addresses
  resources :categories
  resources :products
  resources :order_items
  resources :orders
  resources :wishlist
  devise_for :shops, controllers: { registrations: "registrations" }
  root 'home#index'
  get '/add_to_cart' => 'shopping_cart#add_to_cart', as: :add_to_cart
  get '/removeItem/:order_item_id' => 'shopping_cart#remove_from_cart', as: :remove_from_cart
  get '/addItem/:order_item_id' => 'shopping_cart#add_item', as: :add_item
  get '/minusItem/:order_item_id' => 'shopping_cart#minus_item', as: :minus_item
  get 'payment', to: 'orders#payment'
  get 'confirmations', to: 'orders#confirmations'
  get '/wishlist/' =>'wishlist#wishlist'
  get '/remove_from_list/' => 'wishlist#remove_from_wishlist', as: :remove_from_list
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if Shop.count > 0
      @shop = Shop.last
      @top_products = Product.order(rating: :desc).limit(4)
      @latest_products = Product.last(4)
    else
      redirect_to new_shop_registration_path
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="row">
  <div class="col s2 side-nav-categories">
    <div class=side-nav-categories"">
          <ul>
            <% @shop.categories.each do |cat| %>
              <a href="/categories/<%= cat.id %>">
                <li class="category-link"><%= cat.category_name %></li>
              </a>
            <% end %>
          </ul>
    </div>
  </div>
  <div class="col s10">
    <ul class="bxslider" style="border: 0px;">
    <% @shop.categories.each do |cat| %>
            <div class="shop-banner-landing">
              <% if cat.products.any? %>
              <li>
              <div class="title-banner">
                <h1><%= cat.category_name %></h1>
                  <% prod = cat.products.sample %>
                  <h4><%= prod.product_name %></h4>
              </div>
              <div class="content-banner">
                <div class="text-banner">
                  <p><%= prod.product_description %></p>
                  <span class="money-banner"><%= number_to_currency(prod.price, :unit => 'KES ') %></span>
                </div>
                <div class="offer-banner">
                  <%= link_to 'Shop Now', category_path(cat), class: 'btn-large' %>
                </div>
              </div>
            </li>
            <% end %>
            </div>
      <% end %>
    </ul>
  </div>

</div>

<div class="products-container">
  <h4>Top Products</h4>
  <div class="row">
    <% @top_products.each do |product| %>
      <a href="/products/<%= product.id %>">
        <div class="col s3 ">
          <div class="card" style="padding: 0px;">
            <div class="card-image">
              <li><%= image_tag product.image, class: 'product-card-small', :height => "350px", :width => "150px" %></li>
            </div>
            <div class="card-content">
              <h6><%= product.product_name %></h6>
              <p><%= product.product_description[0, 30] + "..." %> <%= link_to 'more' %></p>
            </div>
            <div class="card-action">
              <div class="row">
          <div class="col s6">
                       <i id= "changeColor" class="material-icons" onclick="addToWishlist(<%= product.id %>)">favorite_border</i>
                 </div> 
                <div class="col s6">
                  <div class="money-tile">
                    <%= number_to_currency(product.price, :unit => ' KES') %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </a>
    <% end %>
  </div>
</div>

<div class="products-container">
  <h4>Latest Products</h4>
  <div class="row">
    <% @latest_products.reverse.each do |product| %>
      <a href="/products/<%= product.id %>">
        <div class="col s3 ">
          <div class="card" style="padding: 0px;">
            <div class="card-image">
              <li><%= image_tag product.image, class: 'product-card-small', :height => "350px", :width => "150px"%></li>
            </div>
            <div class="card-content">
              <h6><%= product.product_name %></h6>
              <p><%= product.product_description[0, 30] + "..." %> <%= link_to 'more' %></p>
            </div>
            <div class="card-action">
              <div class="row">
           <div class="col s6">
            <i id= "changeColor" class="material-icons" onclick="addToWishlist(<%= product.id %>)">favorite_border</i>
                </div> 
                <div class="col s6">
                  <div class="money-tile">
                    <%= number_to_currency(product.price, :unit => ' KES') %>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </a>
    <% end %>
  </div>
</div>