config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :addresses
  resources :categories
  resources :products
  resources :order_items
  resources :orders
  resources :wishlist
  devise_for :shops, controllers: { registrations: "registrations" }
  root 'home#index'
  get '/add_to_cart' => 'shopping_cart#add_to_cart', as: :add_to_cart
  get '/removeItem/:order_item_id' => 'shopping_cart#remove_from_cart', as: :remove_from_cart
  get '/addItem/:order_item_id' => 'shopping_cart#add_item', as: :add_item
  get '/minusItem/:order_item_id' => 'shopping_cart#minus_item', as: :minus_item
  get 'payment', to: 'orders#payment'
  get 'confirmations', to: 'orders#confirmations'
  get '/wishlist/' =>'wishlist#wishlist'
  get '/remove_from_list/' => 'wishlist#remove_from_wishlist', as: :remove_from_list
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VetaShop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <style type="text/css">
       .material-icons.md-24 { font-size: 24px; color: #ff0000 }
    </style>
  </head>
  <% @shop = Shop.last %>
  <header>
    <nav>
    <div class="container">
      <div class="nav-wrapper">
          <% if shop_signed_in? %>
            <%= link_to current_shop.shop_name, root_url, class: 'brand-logo' %>
          <% else %>
            <a href="/" class="brand-logo">VetaShop</a>
          <% end %>
        <ul id="nav-mobile" class="right nav-links">
          <% if shop_signed_in? %>
            <li><%= link_to 'Manage Shop', edit_shop_registration_path %></li>
          <% else %>
            <li><%= link_to 'New Shop', new_shop_registration_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  </header>
  <% if @cart != nil %>
  <% if @cart.order_items.count > 0 %>
    <div id="cart">
      <div class="modal shopping-cart">
        <div class="cart-title">
          <h6>Cart <sub><%= @cart.order_items.count %> Items</sub> </h6>
            <table>
              <thead>
                <th>Item</th>
                <th>Size</th>
                <th>Qty</th>
                <th>Total</th>
              </thead>
              <tbody>
                <% @cart.order_items.each do |item| %>
                  <tr>
                    <td class="td-cart">
                      <%= item.product.product_name %></br>
                      <%= number_to_currency(item.product.price, :unit => ' KES') %>
                    </td>
                    <td>
                      <%= item.size %>
                    </td>
                    <td class="td-cart">
                      <button onclick="minusCartItem(<%= item.id %>)">-</button>
                      <%= item.quantity %>
                      <button onclick="plusCartItem(<%= item.id %>)">+</button>

                    </td>
                    <td class="td-cart"><%= number_to_currency(item.total_cost, :unit => ' KES') %></td>
                    <td> <i class="material-icons small" onclick="removeFromCart(<%= item.id %>)">delete_forever</i> </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
            <% if @cart.sub_total_price != nil %>
              <table>
                <tr>
                  <td>Subtotal</td>
                  <td><%= number_to_currency(@cart.sub_total_price, :unit => ' KES') %></td>
                </tr>
                <tr>
                  <td>VAT
                  <%= @shop.vat_rate %>%</td>
                  <td><%= number_to_currency(@cart.sub_total_price * @shop.vat_rate.to_i / 100, :unit => ' KES') %></td>
                </tr>
                <tr>
                  <td>Total</td>
                  <td><%= number_to_currency(@cart.total_price, :unit => ' KES') %></td>
                </tr>
              </table>
            <% end %>
            <div class="customer-form">
              <h6>Customer Details</h6>
              <%= form_tag orders_path, remote: true do %>
                <%= text_field_tag :client_name, nil, :placeholder => 'Enter Your Name', required: true %>
                <%= number_field_tag :client_phone_number, nil, :placeholder => 'Enter Phone Number', required: true %>
                <%= text_field_tag :delivery, nil, :placeholder => 'Enter Delivery Address', required: true %>
                <%= select_tag :order_payment_method, options_for_select(['Mpesa', 'Card', 'Airtel Money' , 'Cash on Delivery']), class: 'browser-default' %>
                <div class="">
                  <%= submit_tag 'checkout', class: 'btn'%>
                </div>
              <% end %>
            </div>
        </div>
      </div>
    </div>
  <% end %>
  <% end %>
  <body onload="slider()">
    <div class="container">
      <%= yield %>
    </div>
  </body>
  <footer class="page-footer">
    <% if !@shop.nil? %>
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h5 class="white-text"><%= @shop.shop_name %></h5>
          <p class="grey-text text-lighten-4"><%= @shop.tag_line %></p>
        </div>
        <div class="col l4 offset-l2 s12">
          <h5 class="white-text">Contact Information</h5>
          <ul>
            <% @shop.addresses.each do |addr| %>
              <li><%= addr.physical_address %></li>
              <li><%= addr.phone_number %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container">
      © 2020 Copyright <%= @shop.shop_name %>
      <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
      </div>
    </div>
    <% end %>
  </footer>
<script type="text/javascript">
  $(document).ready(function(){
    $('.bxslider').bxSlider();
  });

// var check_quantity = "<%# @product.quantity %>"
// var order_quantity = "<%# @order_item.attributes["quantity"]%>"
// if (check_quantity = check_quantity -  ){
//   $('#inStock').html('Out of Stock')
// }

// var qtys = "<%#@order_item.quantity%>"
// console.log(qtys)

</script>
</html>